pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                bat """
                cd SwagLabs_Automation
                C:\\Users\\yanam\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m pip install -r requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                bat """
                cd SwagLabs_Automation
                C:\\Users\\yanam\\AppData\\Local\\Programs\\Python\\Python313\\python.exe -m pytest -v
                """
            }
        }
    }

    post {
        always {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'SwagLabs_Automation/reports',
                reportFiles: 'report.html',
                reportName: 'PyTest HTML Report'
            ])
        }
    }
}